networks:
  otel-demo-network:
    external: true
    driver: bridge

services:
  amokal_frontend:
    image: otel-demo:frontend
    container_name: amokal_frontend
    build:
      context: ./
      dockerfile: ./src/frontend/Dockerfile
    deploy:
      resources:
        limits:
          memory: 50M
    restart: unless-stopped
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    networks:
      - otel-demo-network
    depends_on:
      search:
        condition: service_started

  search:
    image: otel-demo:search
    container_name: search
    build:
      context: ./
      dockerfile: ./src/search/Dockerfile
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - ${SEARCH_PORT}:${SEARCH_PORT}
    environment:
      - SEARCH_PORT=${SEARCH_PORT}
      - BUSINESS_SEARCH_PORT=${BUSINESS_SEARCH_PORT}
    networks:
      - otel-demo-network
    depends_on:
      business_search:
        condition: service_started

  business_search:
    image: otel-demo:business_search
    container_name: business-search 
    build:
      context: ./
      dockerfile: ./src/business_search/Dockerfile 
    deploy:
      resources:
        limits:
          memory: 50M
    restart: unless-stopped
    ports:
      - ${BUSINESS_SEARCH_PORT}:${BUSINESS_SEARCH_PORT}
    networks:
      - otel-demo-network
